<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "taskqueue"
 *
 * Auto generated by Extension Builder 2014-10-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'task',
	'description' => 'Provides a task queue for other extensions to use.',
	'category' => 'module',
	'author' => 'Eike Starkmann',
	'author_email' => 'starkmann@undkonsorten.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
